--[[
    desc:注册配置
    auth:Carol Luo
]]

return {
    --共享推送映射
    "share.push",
    --共享拉取映射
    "share.fech",
    --麻将成朴映射
    "mahjong.mapHuCards",
    --麻将名字映射
    "mahjong.mapNames",
    --麻将视图映射
    "mahjong.mapViews",
    --麻将成扑隐射
    "mahjong.mapSnaps",
    --扑克名字映射
    "poker.mapNames",
    --服务信息数据
    "listener.mapServers",
    --游戏信息数据
    "games.gameInfos",
    --管理桌子数据
    "sundry.table",
    --管理机器数据
    "sundry.robot",
    --平台比例数据
    "sundry.ratio",
    --编码配置数据
    "sundry.code",
    --百人龙虎配置
    "hundred.games.dragonTiger",
    --金玉满堂配置
    "slots.games.jymtCfg",
    --金鸡报喜配置
    "slots.games.jjbxCfg",
}